version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db
    command: ["node", "index.js"]

  db:
    image: mariadb
    container_name: mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql/
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app